# Generated by Django 5.0.4 on 2024-04-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
    ]
