# Generated by Django 5.0.4 on 2024-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='This is a default description'),
            preserve_default=False,
        ),
    ]
